### ISSUE TITLE
[Bug] <Images.php code error>

### ISSUE THREAD

**Issue by therandomspoon** [GoldDominik893/liberatube#15]
### Where?

Stable

### What version did you encounter this bug on?

v1.7

### List the steps needed to reproduce this bug.

In the images.php code you have it end in .jpg and not .jpeg but according to you file hosting system you use it should be .jpeg. Simple bug to fix probably just a outdated code version

**Comment by GoldDominik893** [comment]
the fix will come soon, i have already made the changes just not published them to github.
